import * as pulumi from "@pulumi/pulumi";
import * as hcloud from "@pulumi/hcloud";
import * as tls from "@pulumi/tls";

export interface ServerConfig {
    name: string;
    serverType: string;
    location: string;
    image: string;
    userData: pulumi.Output<string>;
    firewallId: pulumi.Output<number>;
}

export interface ServerResult {
    server: hcloud.Server;
    sshKey: hcloud.SshKey;
    privateKey: pulumi.Output<string>;
}

/**
 * Creates a Hetzner Cloud server with secure SSH key authentication.
 *
 * Server specs (default cax21 ARM):
 * - 4 vCPU (Ampere Altra)
 * - 8 GB RAM
 * - 80 GB NVMe SSD
 * - 20 TB traffic
 * - €6.49/month
 *
 * Security:
 * - SSH key generated by Pulumi (no password auth)
 * - Attached to firewall with no inbound rules
 * - Cloud-init handles all configuration
 */
export function createServer(config: ServerConfig): ServerResult {
    // Generate SSH key pair using Pulumi TLS provider
    const sshKeyPair = new tls.PrivateKey(`${config.name}-ssh-key`, {
        algorithm: "ED25519",
    });

    // Register SSH public key with Hetzner
    const sshKey = new hcloud.SshKey(`${config.name}-ssh-key`, {
        name: `${config.name}-key`,
        publicKey: sshKeyPair.publicKeyOpenssh,
        labels: {
            project: "openclaw",
            managed_by: "pulumi",
        },
    });

    // Create the server
    const server = new hcloud.Server(config.name, {
        name: config.name,
        serverType: config.serverType,
        location: config.location,
        image: config.image,
        sshKeys: [sshKey.id],
        userData: config.userData,
        firewallIds: [config.firewallId],
        labels: {
            project: "openclaw",
            managed_by: "pulumi",
            environment: "production",
        },
        // Enable backups for disaster recovery
        backups: true,
        // Use cloud-init (included in user-data)
        // No need for additional provisioning
    });

    return {
        server,
        sshKey,
        privateKey: sshKeyPair.privateKeyOpenssh,
    };
}
