import * as pulumi from "@pulumi/pulumi";
import * as hcloud from "@pulumi/hcloud";
import * as tls from "@pulumi/tls";

export interface ServerConfig {
    name: string;
    serverType: string;
    location: string;
    image: string;
    userData: pulumi.Output<string>;
    firewallId: pulumi.Output<number>;
}

export interface ServerResult {
    server: hcloud.Server;
    sshKey: hcloud.SshKey;
    privateKey: pulumi.Output<string>;
}

/**
 * Creates a Hetzner Cloud server with secure SSH key authentication.
 *
 * Server specs (configurable via `pulumi config set serverType`):
 *   cx33 (default):  4 vCPU, 8 GB RAM,  80 GB NVMe, 20 TB traffic, ~€5.49/mo
 *   cx43 (recommended for qmd): 8 vCPU, 16 GB RAM, 160 GB NVMe, 20 TB traffic, ~€9.49/mo
 *
 * Changing serverType triggers an in-place resize (brief power cycle, all data preserved).
 * Disk upgrades are one-way (can't downgrade to a smaller disk type).
 *
 * Security:
 * - SSH key generated by Pulumi (no password auth)
 * - Attached to firewall with no inbound rules
 * - Cloud-init bootstraps Tailscale; Ansible configures the rest
 */
export function createServer(config: ServerConfig): ServerResult {
    // Generate SSH key pair using Pulumi TLS provider
    const sshKeyPair = new tls.PrivateKey(`${config.name}-ssh-key`, {
        algorithm: "ED25519",
    });

    // Register SSH public key with Hetzner
    const sshKey = new hcloud.SshKey(`${config.name}-ssh-key`, {
        name: `${config.name}-key`,
        publicKey: sshKeyPair.publicKeyOpenssh,
        labels: {
            project: "openclaw",
            managed_by: "pulumi",
        },
    });

    // Create the server
    const server = new hcloud.Server(config.name, {
        name: config.name,
        serverType: config.serverType,
        location: config.location,
        image: config.image,
        sshKeys: [sshKey.id],
        userData: config.userData,
        firewallIds: [config.firewallId],
        labels: {
            project: "openclaw",
            managed_by: "pulumi",
            environment: "production",
        },
        // Enable backups for disaster recovery
        backups: true,
        // Cloud-init bootstraps Tailscale only (~1 min).
        // All other configuration is handled by Ansible (triggered by index.ts).
    });

    return {
        server,
        sshKey,
        privateKey: sshKeyPair.privateKeyOpenssh,
    };
}
