---
- name: restart openclaw-gateway
  ansible.builtin.include_tasks:
    file: "{{ playbook_dir }}/roles/openclaw/tasks/restart-gateway.yml"
    apply:
      tags: [always]

- name: reload user systemd
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/1000"
